[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002045854C510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3ca2bc41a52920d7c097e75b27fae306/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002045854CB10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3ca2bc41a52920d7c097e75b27fae306/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002045854D550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3ca2bc41a52920d7c097e75b27fae306/window/maximize