[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ACA6DE8110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bdd167e6e1506055c124847537b59748/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ACA6DE8AD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bdd167e6e1506055c124847537b59748/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ACA6DE9510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bdd167e6e1506055c124847537b59748/window/maximize