[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A84CA40110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/145c99ba68c3260ae646c507ea95b6a9/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A84CA40F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/145c99ba68c3260ae646c507ea95b6a9/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A84CA41990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/145c99ba68c3260ae646c507ea95b6a9/window/maximize