[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000179AB549210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7b5732d90fe0f5a10b8454a2a4b5ce4e/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000179AB54B050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7b5732d90fe0f5a10b8454a2a4b5ce4e/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000179AB54AE90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7b5732d90fe0f5a10b8454a2a4b5ce4e/window/maximize